# Generated by Django 5.0.3 on 2024-03-23 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0001_initial'),
        ('student_app', '0005_student_subjects'),
        ('subject_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='a_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='subject_app.subject'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='student_app.student'),
        ),
    ]
