# Generated by Django 5.0.3 on 2024-03-21 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade_app', '0001_initial'),
        ('student_app', '0006_alter_student_locker_combination_and_more'),
        ('subject_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='a_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_app.subject'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.student'),
        ),
    ]
