# Generated by Django 5.0.3 on 2024-03-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_rename_students_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='locker_number',
            field=models.IntegerField(default=1),
        ),
    ]
