# Generated by Django 5.0.3 on 2024-03-22 00:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(2000)])),
                ('custom', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=25, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('address', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('num_of_vehicles', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('year', models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1920), django.core.validators.MaxValueValidator(2100)])),
                ('number_of_tires', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(5)])),
                ('engine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars_app.engine')),
                ('owners', models.ManyToManyField(to='cars_app.owner')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(default='Unknown', max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('place_of_service', models.CharField(max_length=100)),
                ('notes', models.TextField(default='None')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_app.car')),
            ],
        ),
        migrations.CreateModel(
            name='Tires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_width', models.PositiveIntegerField(default=30)),
                ('aspect_ratio', models.PositiveIntegerField(default=15)),
                ('rim_size', models.PositiveIntegerField(default=16)),
                ('vehicle_type', models.CharField(max_length=30)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars_app.car')),
            ],
        ),
    ]
