# Generated by Django 5.0.3 on 2024-03-28 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_sub_task_parent_task_alter_task_parent_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='users',
            field=models.ManyToManyField(related_name='lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
